# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\kamil\Desktop\tp_projekt_3\tp_projekt_3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\kamil\Desktop\tp_projekt_3\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\kamil\Desktop\tp_projekt_3\build\CMakeFiles C:\Users\kamil\Desktop\tp_projekt_3\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\kamil\Desktop\tp_projekt_3\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named plot

# Build rule for target.
plot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 plot
.PHONY : plot

# fast build rule for target.
plot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\plot.dir\build.make CMakeFiles/plot.dir/build
.PHONY : plot/fast

#=============================================================================
# Target rules for targets named planar_quadrotor

# Build rule for target.
planar_quadrotor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 planar_quadrotor
.PHONY : planar_quadrotor

# fast build rule for target.
planar_quadrotor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/build
.PHONY : planar_quadrotor/fast

#=============================================================================
# Target rules for targets named nodesoup

# Build rule for target.
nodesoup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 nodesoup
.PHONY : nodesoup

# fast build rule for target.
nodesoup/fast:
	$(MAKE) $(MAKESILENT) -f matplotplusplus\source\3rd_party\CMakeFiles\nodesoup.dir\build.make matplotplusplus/source/3rd_party/CMakeFiles/nodesoup.dir/build
.PHONY : nodesoup/fast

#=============================================================================
# Target rules for targets named matplot

# Build rule for target.
matplot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 matplot
.PHONY : matplot

# fast build rule for target.
matplot/fast:
	$(MAKE) $(MAKESILENT) -f matplotplusplus\source\matplot\CMakeFiles\matplot.dir\build.make matplotplusplus/source/matplot/CMakeFiles/matplot.dir/build
.PHONY : matplot/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f SDL\CMakeFiles\sdl_headers_copy.dir\build.make SDL/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f SDL\CMakeFiles\SDL2main.dir\build.make SDL/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2

# Build rule for target.
SDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL2
.PHONY : SDL2

# fast build rule for target.
SDL2/fast:
	$(MAKE) $(MAKESILENT) -f SDL\CMakeFiles\SDL2.dir\build.make SDL/CMakeFiles/SDL2.dir/build
.PHONY : SDL2/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f SDL\CMakeFiles\SDL2-static.dir\build.make SDL/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f SDL\CMakeFiles\SDL2_test.dir\build.make SDL/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f SDL\CMakeFiles\uninstall.dir\build.make SDL/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named SDL2_gfx

# Build rule for target.
SDL2_gfx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 SDL2_gfx
.PHONY : SDL2_gfx

# fast build rule for target.
SDL2_gfx/fast:
	$(MAKE) $(MAKESILENT) -f SDL2_gfx\CMakeFiles\SDL2_gfx.dir\build.make SDL2_gfx/CMakeFiles/SDL2_gfx.dir/build
.PHONY : SDL2_gfx/fast

PlanarQuadrotor/lqr.obj: PlanarQuadrotor/lqr.cpp.obj
.PHONY : PlanarQuadrotor/lqr.obj

# target to build an object file
PlanarQuadrotor/lqr.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/lqr.cpp.obj
.PHONY : PlanarQuadrotor/lqr.cpp.obj

PlanarQuadrotor/lqr.i: PlanarQuadrotor/lqr.cpp.i
.PHONY : PlanarQuadrotor/lqr.i

# target to preprocess a source file
PlanarQuadrotor/lqr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/lqr.cpp.i
.PHONY : PlanarQuadrotor/lqr.cpp.i

PlanarQuadrotor/lqr.s: PlanarQuadrotor/lqr.cpp.s
.PHONY : PlanarQuadrotor/lqr.s

# target to generate assembly for a file
PlanarQuadrotor/lqr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/lqr.cpp.s
.PHONY : PlanarQuadrotor/lqr.cpp.s

PlanarQuadrotor/planar_quadrotor.obj: PlanarQuadrotor/planar_quadrotor.cpp.obj
.PHONY : PlanarQuadrotor/planar_quadrotor.obj

# target to build an object file
PlanarQuadrotor/planar_quadrotor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/planar_quadrotor.cpp.obj
.PHONY : PlanarQuadrotor/planar_quadrotor.cpp.obj

PlanarQuadrotor/planar_quadrotor.i: PlanarQuadrotor/planar_quadrotor.cpp.i
.PHONY : PlanarQuadrotor/planar_quadrotor.i

# target to preprocess a source file
PlanarQuadrotor/planar_quadrotor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/planar_quadrotor.cpp.i
.PHONY : PlanarQuadrotor/planar_quadrotor.cpp.i

PlanarQuadrotor/planar_quadrotor.s: PlanarQuadrotor/planar_quadrotor.cpp.s
.PHONY : PlanarQuadrotor/planar_quadrotor.s

# target to generate assembly for a file
PlanarQuadrotor/planar_quadrotor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/planar_quadrotor.cpp.s
.PHONY : PlanarQuadrotor/planar_quadrotor.cpp.s

PlanarQuadrotor/planar_quadrotor_visualizer.obj: PlanarQuadrotor/planar_quadrotor_visualizer.cpp.obj
.PHONY : PlanarQuadrotor/planar_quadrotor_visualizer.obj

# target to build an object file
PlanarQuadrotor/planar_quadrotor_visualizer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/planar_quadrotor_visualizer.cpp.obj
.PHONY : PlanarQuadrotor/planar_quadrotor_visualizer.cpp.obj

PlanarQuadrotor/planar_quadrotor_visualizer.i: PlanarQuadrotor/planar_quadrotor_visualizer.cpp.i
.PHONY : PlanarQuadrotor/planar_quadrotor_visualizer.i

# target to preprocess a source file
PlanarQuadrotor/planar_quadrotor_visualizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/planar_quadrotor_visualizer.cpp.i
.PHONY : PlanarQuadrotor/planar_quadrotor_visualizer.cpp.i

PlanarQuadrotor/planar_quadrotor_visualizer.s: PlanarQuadrotor/planar_quadrotor_visualizer.cpp.s
.PHONY : PlanarQuadrotor/planar_quadrotor_visualizer.s

# target to generate assembly for a file
PlanarQuadrotor/planar_quadrotor_visualizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/planar_quadrotor_visualizer.cpp.s
.PHONY : PlanarQuadrotor/planar_quadrotor_visualizer.cpp.s

PlanarQuadrotor/simulate.obj: PlanarQuadrotor/simulate.cpp.obj
.PHONY : PlanarQuadrotor/simulate.obj

# target to build an object file
PlanarQuadrotor/simulate.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/simulate.cpp.obj
.PHONY : PlanarQuadrotor/simulate.cpp.obj

PlanarQuadrotor/simulate.i: PlanarQuadrotor/simulate.cpp.i
.PHONY : PlanarQuadrotor/simulate.i

# target to preprocess a source file
PlanarQuadrotor/simulate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/simulate.cpp.i
.PHONY : PlanarQuadrotor/simulate.cpp.i

PlanarQuadrotor/simulate.s: PlanarQuadrotor/simulate.cpp.s
.PHONY : PlanarQuadrotor/simulate.s

# target to generate assembly for a file
PlanarQuadrotor/simulate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\planar_quadrotor.dir\build.make CMakeFiles/planar_quadrotor.dir/PlanarQuadrotor/simulate.cpp.s
.PHONY : PlanarQuadrotor/simulate.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\plot.dir\build.make CMakeFiles/plot.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\plot.dir\build.make CMakeFiles/plot.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\plot.dir\build.make CMakeFiles/plot.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... sdl_headers_copy
	@echo ... uninstall
	@echo ... SDL2
	@echo ... SDL2-static
	@echo ... SDL2_gfx
	@echo ... SDL2_test
	@echo ... SDL2main
	@echo ... matplot
	@echo ... nodesoup
	@echo ... planar_quadrotor
	@echo ... plot
	@echo ... PlanarQuadrotor/lqr.obj
	@echo ... PlanarQuadrotor/lqr.i
	@echo ... PlanarQuadrotor/lqr.s
	@echo ... PlanarQuadrotor/planar_quadrotor.obj
	@echo ... PlanarQuadrotor/planar_quadrotor.i
	@echo ... PlanarQuadrotor/planar_quadrotor.s
	@echo ... PlanarQuadrotor/planar_quadrotor_visualizer.obj
	@echo ... PlanarQuadrotor/planar_quadrotor_visualizer.i
	@echo ... PlanarQuadrotor/planar_quadrotor_visualizer.s
	@echo ... PlanarQuadrotor/simulate.obj
	@echo ... PlanarQuadrotor/simulate.i
	@echo ... PlanarQuadrotor/simulate.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

